apiVersion: platform.paved.dev/v1alpha1
kind: ServiceClaim
metadata:
  name: shortlink
  namespace: platform-claims
spec:
  owner: team-growth
  image: k3d-paved-registry:5001/shortlink:0.1.0
  port: 8080
  tier: internal
  sli:
    type: http-availability
  slo:
    objective: "99.9"
    window: 28d
  scale:
    min: 2
    max: 4
